[package]
name = "fluid_sdl2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.35.1"
colorgrad = "0.5.0"
fluid_engine = {path = "../fluid_engine"}
